### ISSUE TITLE
Postgres Schema Support

### ISSUE THREAD

**Issue by Barlog951** [toluaina/pg-sync#13]
Hi all

Is here some possibility of how to sync psql schemas ?

Thanks

**Comment by toluaina** [comment]
Are you referring to specifying different Postgres schemas rather than just the default? Yes, I can add support for that.

**Comment by Barlog951** [comment]
> Are you referring to specifying different Postgres schemas rather than just the default? Yes, I can add support for that.

Yes exactly
I have the situation with one DB and 10 schemas with data

I would like to have config like this sample

```
[{
    "index": "my-index",
    "database": "my-db",
    "schema": "my-schema",
    "nodes": [
        {
            "columns": [
                "id" .....
            ],
            "table": "my-table"
    }]
}]
```

Thank you :)

**Comment by toluaina** [comment]
version 1.1.0 now supports multiple schemas

**Comment by toluaina** [comment]
Closing as this has been resolved
