### ISSUE TITLE
Amazon RDS superuser permission error

### ISSUE THREAD

**Issue by sdreger** [toluaina/pg-sync#16]
PGSync version: 1.1.1

Postgres version: 11.2-R1 (AWS RDS Managed)

Elasticsearch version: 7.4

Redis version: 6.0.4

Python version: 3.7.6

Problem Description: Looks like I can connect to the DB, because I don't get an error (like I get with wrong credentials). But after start (either through Docker, or from CLI) I see the following:
```sh
...
redis_1   | 1:M 01 Jun 2020 17:38:37.461 # Server initialized
```
And the system didn't show anything for about 10 minutes, then I got the following error:

Error Message: 
```
pgsync.exc.SuperUserError: 'You need to be a superuser to perform this action: Current user: master'
```

I gave the following permissions to the __master__ role:
```sql
 grant rds_superuser to master;
 grant rds_replication to master;
```

Also I set the __rds.logical_replication__ static parameter to 1, as described here: [To enable logical decoding for an Amazon RDS for PostgreSQL DB instance](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html)

After that, I could create replication slots as the __master__ role.

Then I looked at the __pg_catalog.pg_user__ table:
```sql
SELECT usesuper, userepl FROM pg_user WHERE usename = 'master';
```
The result is: false, false

I think this also related to RDS internal implementation.

And I can not give __superuser__ or __replication__ permissions to the __master__ role because of RDS specificity. When I try to perform the following query:
```sql
grant superuser to master;
```
I get the following error: __ERROR:  role "superuser" does not exist.__

The same error for the __replication__ permission.

I'm not sure if there is a way to check the ability to create replication slots in AWS RDS without performing the following query:
```sql
SELECT usesuper FROM pg_user WHERE usename = 'master';
```

**Comment by tainaandela** [comment]
Did you try with this command:
`ALTER USER master WITH SUPERUSER`

**Comment by toluaina** [comment]
Did you try with this command:
`ALTER USER master WITH SUPERUSER`

**Comment by sdreger** [comment]
Just tried: `ALTER USER master WITH SUPERUSER;`:
```
ERROR:  must be superuser to alter superusers.
```

**Comment by AdityaAnand1** [comment]
Any updates on this? Does this work with RDS?

**Comment by AdityaAnand1** [comment]
As per this:https://serverfault.com/questions/661661/why-cant-i-create-a-superuser-in-aws-postgresql-instance

There is no way to get superuser access with RDS. Does that mean there's no way to make pg-sync work with RDS? Any ideas? @toluaina @chokosabe @Densol92

**Comment by toluaina** [comment]
I deliberately left this open as I am still investigating how to achieve this with RDS

**Comment by Payop** [comment]
Hi @toluaina

I got the same issue.  Do you have any updates on it?

**Comment by toluaina** [comment]
@Payop I have an idea on how to do this. I'm in the middle of completing docs.
I will get back to it very in a day or two.

**Comment by toluaina** [comment]
I've released version 1.1.10 that supports AWS RDS @Payop @sdreger. Can you try this out?

**Comment by toluaina** [comment]
I'm pretty sure this is working now. Closing this for now

**Comment by sdreger** [comment]
I can confirm that it works with RDS now, thanks @toluaina .
