### ISSUE TITLE
Some count indices

### ISSUE THREAD

**Issue by masterlexa** [toluaina/pg-sync#17]
PGSync version: 1.1.1

Postgres version: 9.6

Elasticsearch version: 7.7.1

Redis version: latest

Python version: 3.8

Problem Description: 

What to do with some count indices?
For example, I want to load indices with the scheme:

[
  {
    "database": "main",
    "index": "brand",
    "nodes": [
      {
        "table": "brand",
        "schema": "public",
        "columns": [
          "id",
          "name",
          "approved",
          "popularity"
        ]
      }
    ]
  },
  {
    "database": "main",
    "index": "company",
    "nodes": [
      {
        "table": "company",
        "schema": "public",
        "columns": [
          "id",
          "user_id",
          "organizational_form",
          "disabled"
        ]
      }
    ]
  }
]

**Comment by masterlexa** [comment]
I see it supports it, but load only first index

**Comment by toluaina** [comment]
actually reopening this as this is already in progresss

**Comment by toluaina** [comment]
Thanks for reporting this. 
This is resolved in version 1.1.2

**Comment by masterlexa** [comment]
Thanks!

**Comment by masterlexa** [comment]
It loads only first index in the scheme

**Comment by masterlexa** [comment]
Exception in thread Thread-53:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "pgsync/sync.py", line 641, in pgsync.sync.Sync.poll_redis
  File "pgsync/redisqueue.py", line 73, in pgsync.redisqueue.RedisQueue.bulk_pop
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by toluaina** [comment]
can you re-bootstrap the database which should re-create the trigger 
`bootstrap -t -c path/to/schema.json`

also, delete the hidden file _**.main**_

**Comment by masterlexa** [comment]
I did it, but after creating the first index it makes file **.main** and skips the creation next indices.
Now I have trouble with updating big rows. https://github.com/toluaina/pg-sync/issues/19
I have load indices separately.

**Comment by toluaina** [comment]
OK that fine. 1.1.3 allows you to load in the same schema as well

**Comment by masterlexa** [comment]
Good, but now I see changes the same changes in different slots 
for example 
select * from PG_LOGICAL_SLOT_PEEK_CHANGES('main_company', NULL, NULL)
select * from PG_LOGICAL_SLOT_PEEK_CHANGES('main_brand', NULL, NULL)
select * from PG_LOGICAL_SLOT_PEEK_CHANGES('main_category', NULL, NULL)
make me the same result, and save all data before reload

**Comment by masterlexa** [comment]
and can you change the condition of adding a trigger, now the trigger is added to absolutely all tables in the database (I have> 200). For example a table should trigger if it is in the schema.
Now  > 200 tables have a trigger

**Comment by toluaina** [comment]
- the latest version 1.1.4 only creates triggers for tables in the schema
- we still need to have a database/index pair for each replication slot as this is a requirement.

**Comment by masterlexa** [comment]
Now triggers have tables in the last index in the schema, because after creating the first index, the next creating will drop last triggers.

**Comment by masterlexa** [comment]
But I don't know why I see changes from any tables in each slot

**Comment by toluaina** [comment]
I get what you mean. This is now fixed in 1.1.5. Can you give it a try and let me know

**Comment by masterlexa** [comment]
Good, but how to connect it to New relic, I wrote settings in env, but it doesnt work

**Comment by masterlexa** [comment]
Does it work with standart replication master-slave together?

**Comment by toluaina** [comment]
> Good, but how to connect it to New relic, I wrote settings in env, but it doesnt work

Did you start with `newrelic-admin run-program pgsync ...`

**Comment by toluaina** [comment]
> Does it work with standart replication master-slave together?

Yes I see no reason why this would not work
