### ISSUE TITLE
Add a proper tutorial

### ISSUE THREAD

**Issue by AdityaAnand1** [toluaina/pg-sync#20]
It's a little hard to figure out how to get started with this. It starts off with ` docker-compose up`, should I pull the repo first?, then it uses a random dummy schema instead of instructing the user how they can build their own (instructions for which I'm unable to find anywhere)

Let's improve the readme and add a proper onboarding style tutorial, simple clear instructions. Do this for a quick sample, do these steps for getting it up and running on your own Postgresql/elasticsearch instances, type in these configuration variables, some best practices and off you go.

Something like this would be ideal 😁

**Comment by AdityaAnand1** [comment]
I have these questions right now, that I can't find the answer to:

1. Do I have to clone the project to get started?
2. If yes to 1., then perhaps wouldn't it be better to just stick an image up on docker hub and all the user needs is the docker compose file?
3. Where do I enter the endpoints and credentials for my DB/ES cluster?

Any successful FOSS project has to be marketed as a sort of real product with clear benefits and instructions. I'm more than happy to provide feedback :) I think this is a one of a kind tool and hope that this issue gets serious consideration.

**Comment by toluaina** [comment]
Sorry for the lack of proper documentation.  This will be expedited soon,

1. You don't have to clone the project, You can simply install using pip
2. Docker is one way of running it and there is a docker file compose in the repo. You can clone and run docker-compose up
3. You can add the credentials as environment variables or create a .env file with the environment variables

**Comment by toluaina** [comment]
Plenty of documentation now on the homepage.
