### ISSUE TITLE
What is bootstrap command?

### ISSUE THREAD

**Issue by AdityaAnand1** [toluaina/pg-sync#23]
And how can it be installed? I see no mention anywhere.
![image](https://user-images.githubusercontent.com/13274079/86130553-f18afa80-bb01-11ea-802c-7df03cf46777.png)

**Comment by toluaina** [comment]
`bootstrap` setups up database triggers and the replication slot for pgsync
it is available when you install pgsync using pip install...

**Comment by toluaina** [comment]
Closing this as well as there is no feedback

**Comment by EgoPingvina** [comment]
I install `pgsync` via `pip`, but it doesn`t work

![image](https://user-images.githubusercontent.com/9804340/129577396-a3809889-d48e-4673-9159-95782d730535.png)
