### ISSUE TITLE
bootstrap on schemas

### ISSUE THREAD

**Issue by masterlexa** [toluaina/pg-sync#27]
PGSync version: 1.1.5

Postgres version: 9.6

Elasticsearch version: 7.7.1

Redis version: latest

Python version: 3.7

Problem Description: 
bootstrap makes triggers on different schemas for tables with the same name.
For example:
-public
 --table1
-my_schema
--table1

it makes triggers in public and my_shema but remove only from the public.

Error Message (if any): 

```


```

**Comment by toluaina** [comment]
You are right. There was a bug when tearing down secondary schemas. This has been resolved in version 1.1.6
