### ISSUE TITLE
Does it support bulk/batch sync?

### ISSUE THREAD

**Issue by binfeng** [toluaina/pg-sync#28]
Does it support bulk/batch sync?

**Comment by toluaina** [comment]
it always syncs in bulk. 

You can further tune the sync throughput with the environment variables:

- **QUERY_CHUNK_SIZE=10000** (_number of records to fetch from db at a time_)
- **ELASTICSEARCH_CHUNK_SIZE=2000** (_number of documents to index at a time_)
- **REDIS_CHUNK_SIZE=1000** (_number of items to read from Redis at a time_)

**Comment by toluaina** [comment]
closing issue
