### ISSUE TITLE
missing .env.sample file when building.

### ISSUE THREAD

**Issue by duycuong87vn** [toluaina/pg-sync#3]
hi @toluaina ,
I don't see .env.sample file when building,
What is special in that?

`ERROR: Service 'pgsync' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder050697468/.env.sample: no such file or directory`

**Comment by toluaina** [comment]
Sorry about this. 
I've updated the docker-compose file. 
You should be able to build it now.

**Comment by toluaina** [comment]
Resolved in the latest trunk as well
