### ISSUE TITLE
More Schema Docs

### ISSUE THREAD

**Issue by sivy** [toluaina/pg-sync#32]
There is a need for more complete docs for the behavior in `schema.json`. For instance:

### What would configuring multiple `nodes` in a given database/index do? 

```
[
    {
        "database": "mydb",
        "index": "mydb-index",
        "nodes": [
            {
                "table": "table1",
                "schema": "public",
                "columns": []
           },
           {
                 "table": "table2",
                 "schema": "public",
                 "columns": []
           }
      }
]
```

### What are the possible values of `variant` and what do they do?

In the example I see:

-  "variant": "object"
-  "variant": "scalar"

I did try "nested" once to see if it would work and it blew up 😬 

### Renaming Attributes

The README describes renaming columns:

You can also configure PGSync to rename attributes via the schema config e.g

  {
      "isbn": "9781471331435",
      "this_is_a_custom_title": "1984",
      "desc": "1984 was George Orwell’s chilling prophecy about the dystopian future",
      "contributors": ["George Orwell"]
  }

But I cannot find a reference or docs for what the schema.json would look like to rename an attribute.

**Comment by toluaina** [comment]
Documentation is incomplete and this is on my todo list.

1. What would configuring multiple nodes in a given database/index do?

_Configuring multiple database/index is a way of maintaining one schema.json 
for all database/index pairs you want to sync.
For example, you might want to sync the same database to 2 different 
Elasticsearch indices._

2. What are the possible values of **variant** and what do they do?

Possible variants are "object" and "scalar".
An object maps to a dictionary type while a "scalar" maps to a list.

3. Renaming Attributes

  I apologize. The documentation in this area is non-existent.
  You can rename a column with the transform attribute.
  Here is an example:
      
```
{
    "database": "book",
    "index": "book",
    "nodes": [
        {
            "table": "book",
            "columns": [
                "isbn",
                "title",
                "description"
            ],
            "transform": {
                "rename": {
                    "isbn": "book_isbn",
                    "title": "book_title"
                }
            }
        }
    ]
}

```

**Comment by sivy** [comment]
Thanks @toluaina!
