### ISSUE TITLE
first database integration.

### ISSUE THREAD

**Issue by pgsyncforuser** [toluaina/pg-sync#34]
PGSync version: latest

Postgres version: 12.4

Elasticsearch version: 7.7.0

Redis version: 6.0.6

Python version: 3.7.9

Problem Description: first database integration.

Error Message (if any): 
hi, pgsync works by default. my problem is not being able to integrate my own database.

Os : debian 

~ / docker / pgsync $ docker-compose run pgsync bootstrap --config examples / db / schema.json

Starting pgsync_pg_admin_1 ... done
Starting pgsync_elasticsearch_1 ... done
Starting pgsync_postgres_1 ... done
Starting pgsync_redis_1 ... done
Traceback (most recent call last):
  File "/ usr / local / bin / bootstrap", line 59, in <module>
    main ()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main (* args, ** kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke (ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke (self.callback, ** ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback (* args, ** kwargs)
  File "/ usr / local / bin / bootstrap", line 44, in main
    config = get_config (config)
  File "pgsync / utils.py", line 430, in pgsync.utils.get_config
OSError: Schema config "examples / db / schema.json" not found

**Comment by toluaina** [comment]
I have added some documentation to the homepage on how to configure the schema config. 
might be easier to adapt the examples directory as you also need to edit the Dockerfile

**Comment by toluaina** [comment]
I think you need to ensure "examples/db/schema.json" is present in the container

**Comment by pgsyncforuser** [comment]
Thank you for your help.
I'm missing something
![Screenshot from 2020-08-29 00-29-20](https://user-images.githubusercontent.com/70373042/91617835-8fc7ff00-e991-11ea-83ba-262724c9f342.png)
![Screenshot from 2020-08-29 00-35-17](https://user-images.githubusercontent.com/70373042/91617840-9191c280-e991-11ea-89de-d13d4886e481.png)
![Screenshot from 2020-08-29 00-36-25](https://user-images.githubusercontent.com/70373042/91617843-92c2ef80-e991-11ea-974d-120d3c2d68bf.png)

**Comment by toluaina** [comment]
Ok I see, you need to have a folder in **examples** named **db**. This should be similar to **airbnb**.
The Docker file is using airbnb. 
Alternatively, can you post your schema and database name

**Comment by pgsyncforuser** [comment]
hello, now i just changed the database name everything else is default
![Screenshot from 2020-09-01 13-22-52](https://user-images.githubusercontent.com/70373042/91838875-d601b480-ec56-11ea-8778-bc72a5b737e6.png)
![Screenshot from 2020-09-01 13-31-54](https://user-images.githubusercontent.com/70373042/91839385-a1dac380-ec57-11ea-829d-2115b704a0a2.png)

**Comment by toluaina** [comment]
- You need to set the correct database name in the docker-compose.yml [here](https://github.com/toluaina/pg-sync/blob/master/docker-compose.yml#L11)
- Also, change **airbnb** to your directory in [runserver.sh](https://github.com/toluaina/pg-sync/blob/master/docker/runserver.sh)
- finally, perhaps do a `docker-compose down` followed by `docker-compose up `

**Comment by toluaina** [comment]
I suspect your folder is not copied to the container. 
Try rebuilding the container  `docker-compose up --build --force-recreate `

**Comment by pgsyncforuser** [comment]
thank you it worked just fine. 
I updated the dockerfile and then ran docker-compose up --build --force-recreate.

**Comment by toluaina** [comment]
Good to know its working now
