### ISSUE TITLE
db to elasticsearch 

### ISSUE THREAD

**Issue by pgsyncforuser** [toluaina/pg-sync#36]
PGSync version: latest

Postgres version: 12-alpine 

Elasticsearch version: 7.7.0               

Redis version: latest

Python version: 3.7 

OS : Debian

Problem Description: 

Hi Tolu Aina,
The system is running, but the data added to the database is not visible on the elasticsearch side. Where can I go wrong?

[
    { "database":"db",
        "index":"table",
        "nodes":[
        
            {
                "table": "table_name",
                "schema": "public",
                "columns": [
                ]
            }
            ]
       }
]       

# pgsync -c examples/db/table_name.json
 - table_name
 [==================================================] 100.0% 
main ((), {'config': 'examples/db/table_name.json', 'daemon': False, 'password': False, 'user': None, 'host': None, 'port': None, 'verbose': False}) 0.7559013366699219 secs

postgres  db
trigger 

table_name_notify ->active
table_name_truncate -> active

insert into table_name.... -> successfully

http://localhost:9201/table/_search?q=e

{"took":2,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}

**Comment by toluaina** [comment]
- is this running under docker?
- my guess is that you are modifying the schema. 
- I think you need to delete the checkpoint file and re-run pgsync
  ` rm .db_table`
  `pgsync -c examples/db/table_name.json`

**Comment by pgsyncforuser** [comment]
actually there is more than one schema.
how can I do it ?
//table 1
[
    { "database":"db",
        "index":"table",
        "nodes":[
        
            {
                "table": "table_name",
                "schema": "public",
                "columns": [
                ]
            },

            ]
       }
]


//table 2
[
    { "database":"db",
        "index":"table",
        "nodes":[
        
            {
                "table": "table_name",
                "schema": "public",
                "columns": [
                ]
            },

            ]
       }
]

or 

[
    { "database":"db",
        "index":"table",
        "nodes":[
        
            {
                "table": "table_name1",
                "schema": "public",
                "columns": [
                ]
            },
           {
                "table": "table_name2",
                "schema": "public",
                "columns": [
                ]
            },

            ]
       }
]

**Comment by toluaina** [comment]
Do you mean more than one index?
It depends on what you are trying to achieve.


You can use this schema to have 2 ES indices 

```
[
    {
        "database": "db",
        "index": "table1",
        "nodes": [
            {
                "table": "table_name1"
            }
        ]
    },
    {
        "database": "db",
        "index": "table2",
        "nodes": [
            {
                "table": "table_name2"
            }
        ]
    }
]
```

**Comment by pgsyncforuser** [comment]
Thanks @toluaina!
