### ISSUE TITLE
Add support for foreign tables

### ISSUE THREAD

**Issue by judasane** [toluaina/pg-sync#37]
PGSync version: 
1.1.10
Postgres version: 
12.3
Elasticsearch version: 
7.2
Redis version: 
2.4.5
Python version: 
3.8
Problem Description: 
When trying to get data from a postgresql foreign table it is not found 

Error Message (if any): 

```
pgsync.exc.TableNotFoundError: 'Table "main_database_foreign_schema.contacts" not found in registry'
```

**Comment by toluaina** [comment]
Foreign keys are supported via relationships. 
See how to define relationships [here](https://pgsync.com/tutorial/relationship-with-one-to-many-type/) 
can you share a snippet of your schema?

**Comment by toluaina** [comment]
Closing as this has hopefully be addressed in the highlighted docs
