### ISSUE TITLE
Connect to Postgres in SSL mode?

### ISSUE THREAD

**Issue by CE-Creates** [toluaina/pg-sync#38]
Problem Description: 

We have an encrypted postgreSQL database on AWS RDS to which we connect via SSL key (managed by AWS KMS)
How can we achieve the same with pgsync. Couldn't find any info regarding SSL in the documentations

Here is our ENV: 

```
### Elastic Search Variables
export ELASTICSEARCH_SCHEME=https
export ELASTICSEARCH_HOST=xxx.aws.cloud.es.io
export ELASTICSEARCH_PORT=9243
export ELASTICSEARCH_USER=xxx
export ELASTICSEARCH_PASSWORD=xxx
export ELASTICSEARCH_TIMEOUT=10

### PostgreSQL Variables
export PG_HOST=xxx.rds.amazonaws.com
export PG_USER=xxxx
export PG_PASSWORD=xxx
export PG_PORT=5432

### Redis Variables
export REDIS_HOST=xxx.cache.amazonaws.com
export REDIS_PORT=6379

```

which env variable should we set to point to the cert file?

**Comment by toluaina** [comment]
This is now supported in version 1.1.12.
You'll need to set:

- PG_SSLMODE
- PG_SSLROOTCERT

The full list of environment variables are documented [here](https://pgsync.com/env-vars/).

**Comment by CE-Creates** [comment]
@toluaina Thanks a bunch for your prompt reply. 
A couple of questions before I can try above
1) How do we check the current vesion? pgsync --version doesnt work now. 
2) How to upgrade pgsync?

**Comment by toluaina** [comment]
Good point. I will add a command argument for displaying the version.

For now, you can open a python shell and do:
```
import pgsync
pgsync.__version__
```

You can upgrade pgsync using pip

`pip install pgsync --upgrade`

**Comment by CE-Creates** [comment]
The documentation says PG_SSLROOTCERT should have the name of a file containing SSL certificate authority (CA) certificate(s). Are you sure its just the name? does pgsync expect this file to be in some standard folder like ~/.ssh ?

**Comment by toluaina** [comment]
**PG_SSLROOTCERT** needs to be the path to the file containing SSL certificate authority (CA) certificate(s).
It is the same as the **_sslrootcert_** parameter outlined [here](https://www.postgresql.org/docs/current/libpq-connect.html).

**Comment by CE-Creates** [comment]
ok thanks. 

Another question. I cant seem to import pgsync from python console.
am I missing anything ?

**Comment by toluaina** [comment]
Can you check your virtualenv is activated if applicable?
pgsync should be installed to site-packages 

You should be able to import pgsync once you've installed it.

Maybe try this in a new environemtn.

- virtualenv -p python3 venv
- source venv/bin/activate  
- python -c "import pgsync; print(pgsync.__version__)"

**Comment by toluaina** [comment]
Closing as this has been resolved. Reopen if there are outstanding issues.
