### ISSUE TITLE
Works with App Search?

### ISSUE THREAD

**Issue by Luiz-N** [toluaina/pg-sync#40]
Will this library work with the elastic search App Search engine? Any caveats to know about?

**Comment by toluaina** [comment]
I am not super familiar with App Search engine but I see no reason why not. 

Elasticsearch itself still underpins the App Search engine.
App Search engine sits on top of the Elasticsearch core so you should be able to 
leverage PGSync

**Comment by Luiz-N** [comment]
we started up an app search deployment then ran a pg-sync using the underlying elastic search instance. The sync was able to create an ES index but we weren't able to see the data in the App Search Engine dashboard... it seems the indexes need to be tagged or handled differently.
