### ISSUE TITLE
How can we run pgsync as a background job?

### ISSUE THREAD

**Issue by CE-Creates** [toluaina/pg-sync#41]
I am able to run pgsync once and it works well.
However, it gets killed if I try with --daemon.
What is the best practice to get this running as a background job in a production like environment ?
I am afraid if the process would get killed if the terminal is detached even if I get to run it with --daemon. I tried with nohup but it still get killed.

**Comment by toluaina** [comment]
`--daemon` is not behaving like a true daemon.
It simply enables it to run continuously and as long as the tty is not detached.

You could try:
`nohup pgsync -c examples/book/schema.json --daemon &`

Implementing a real daemon would be beyond the scope of pgsync 
as there are better tools for doing this already.

I would suggest you use something like Systemd.
I found [this](https://tecadmin.net/setup-autorun-python-script-using-systemd/) little walk-through that might help.

@CE-Creates

**Comment by toluaina** [comment]
Great closing for now
