### ISSUE TITLE
sync.py

### ISSUE THREAD

**Issue by arvindkhadri** [toluaina/pg-sync#7]
PGSync version: 
1.0.1

Hi. First of all, great project. 😃 
I was browsing through the code base just to understand how it works and was trying to figure out where sync.py is?

**Comment by toluaina** [comment]
Thanks. PGSync will be released under an open-source licence soon. At the moment, it is provided in a binary distribution.

**Comment by arvindkhadri** [comment]
Looking forward to that. 

Thanks.
